version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=!Password1
    ports:
      - '5432:5432'
    container_name: supercarga-db
    volumes: 
      - c:/opt/supercarga/data:/var/lib/postgresql/data
      - c:/opt/supercarga/backup:/var/lib/postgresql/backup
volumes:
  db:
    driver: local